import {
  UserProfile,
  Student,
  Teacher,
  Course,
  Subject,
  AttendanceRecord,
  MarkRecord,
  Assignment,
  AssignmentSubmission,
  Exam,
  TimetableSlot,
  Notice,
  CollegeEvent,
  Certificate,
  ResumeData,
  NotificationItem,
} from '../types';

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: 'user-student-1',
    full_name: 'Alex Johnson',
    email: 'student@university.edu',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    phone: '+1 555-0192',
    gender: 'Male',
    dob: '2003-05-14',
    address: '42 University Heights, Campus Town',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-2',
    full_name: 'Priya Sharma',
    email: 'priya.sharma@university.edu',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    phone: '+1 555-0193',
    gender: 'Female',
    dob: '2003-11-20',
    address: '18 Tech Hostel, North Campus',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-3',
    full_name: 'Rahul Patel',
    email: 'rahul.patel@university.edu',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    phone: '+1 555-0194',
    gender: 'Male',
    dob: '2002-09-03',
    address: '77 Student Row, West Campus',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-4',
    full_name: 'Emma Watson',
    email: 'emma.w@university.edu',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    phone: '+1 555-0195',
    gender: 'Female',
    dob: '2003-02-18',
    address: '104 Innovation Hall',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-5',
    full_name: 'Michael Chen',
    email: 'm.chen@university.edu',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    phone: '+1 555-0196',
    gender: 'Male',
    dob: '2003-07-25',
    address: '22 Science Block',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-teacher-1',
    full_name: 'Dr. Robert Vance',
    email: 'teacher@university.edu',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    phone: '+1 555-0800',
    gender: 'Male',
    dob: '1980-04-12',
    address: 'Faculty Quarters A-12',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-teacher-2',
    full_name: 'Prof. Meera Reddy',
    email: 'meera.reddy@university.edu',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    phone: '+1 555-0801',
    gender: 'Female',
    dob: '1985-08-23',
    address: 'Faculty Quarters B-04',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-teacher-3',
    full_name: 'Dr. Alan Turing',
    email: 'alan.turing@university.edu',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150',
    phone: '+1 555-0802',
    gender: 'Male',
    dob: '1978-06-23',
    address: 'Faculty Quarters C-01',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-admin-1',
    full_name: 'Dr. Eleanor Vance (Dean)',
    email: 'admin@university.edu',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    phone: '+1 555-0999',
    gender: 'Female',
    dob: '1975-01-05',
    address: 'Administration Block Room 101',
    created_at: '2020-01-01T00:00:00Z',
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-1',
    code: 'CSE-BTECH',
    name: 'B.Tech in Computer Science & Engineering',
    department: 'Computer Science',
    description: '4-Year undergraduate program focusing on algorithms, web systems, AI, and software design.',
    duration_years: 4,
    total_semesters: 8,
    active: true,
    student_count: 140,
  },
  {
    id: 'course-2',
    code: 'IT-BTECH',
    name: 'B.Tech in Information Technology',
    department: 'Information Technology',
    description: 'Comprehensive IT program covering networking, cloud computing, and enterprise architecture.',
    duration_years: 4,
    total_semesters: 8,
    active: true,
    student_count: 110,
  },
  {
    id: 'course-3',
    code: 'AIDS-BTECH',
    name: 'B.Tech in Artificial Intelligence & Data Science',
    department: 'AI & Data Science',
    description: 'Advanced degree in machine learning, deep learning, data analysis, and intelligent systems.',
    duration_years: 4,
    total_semesters: 8,
    active: true,
    student_count: 90,
  },
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'teacher-1',
    profile_id: 'user-teacher-1',
    teacher_id_code: 'TCH-1001',
    department: 'Computer Science',
    designation: 'Associate Professor',
    profile: INITIAL_PROFILES[5],
  },
  {
    id: 'teacher-2',
    profile_id: 'user-teacher-2',
    teacher_id_code: 'TCH-1002',
    department: 'Computer Science',
    designation: 'Assistant Professor',
    profile: INITIAL_PROFILES[6],
  },
  {
    id: 'teacher-3',
    profile_id: 'user-teacher-3',
    teacher_id_code: 'TCH-1003',
    department: 'AI & Data Science',
    designation: 'Head of Department',
    profile: INITIAL_PROFILES[7],
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'student-1',
    profile_id: 'user-student-1',
    student_id_code: 'STD-2023-001',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    department: 'Computer Science',
    branch: 'CSE',
    semester: 5,
    section: 'A',
    roll_number: '21CS001',
    admission_year: 2023,
    guardian_name: 'Robert Johnson Sr.',
    guardian_phone: '+1 555-9081',
    guardian_relation: 'Father',
    profile: INITIAL_PROFILES[0],
  },
  {
    id: 'student-2',
    profile_id: 'user-student-2',
    student_id_code: 'STD-2023-002',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    department: 'Computer Science',
    branch: 'CSE',
    semester: 5,
    section: 'A',
    roll_number: '21CS002',
    admission_year: 2023,
    guardian_name: 'Sunil Sharma',
    guardian_phone: '+1 555-9082',
    guardian_relation: 'Father',
    profile: INITIAL_PROFILES[1],
  },
  {
    id: 'student-3',
    profile_id: 'user-student-3',
    student_id_code: 'STD-2023-003',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    department: 'Computer Science',
    branch: 'CSE',
    semester: 5,
    section: 'B',
    roll_number: '21CS003',
    admission_year: 2023,
    guardian_name: 'Mahesh Patel',
    guardian_phone: '+1 555-9083',
    guardian_relation: 'Father',
    profile: INITIAL_PROFILES[2],
  },
  {
    id: 'student-4',
    profile_id: 'user-student-4',
    student_id_code: 'STD-2023-004',
    course_id: 'course-2',
    course_name: 'B.Tech IT',
    department: 'Information Technology',
    branch: 'IT',
    semester: 3,
    section: 'A',
    roll_number: '22IT014',
    admission_year: 2023,
    guardian_name: 'Arthur Watson',
    guardian_phone: '+1 555-9084',
    guardian_relation: 'Father',
    profile: INITIAL_PROFILES[3],
  },
  {
    id: 'student-5',
    profile_id: 'user-student-5',
    student_id_code: 'STD-2023-005',
    course_id: 'course-3',
    course_name: 'B.Tech AI & DS',
    department: 'AI & Data Science',
    branch: 'AIDS',
    semester: 5,
    section: 'A',
    roll_number: '21AI009',
    admission_year: 2023,
    guardian_name: 'David Chen',
    guardian_phone: '+1 555-9085',
    guardian_relation: 'Father',
    profile: INITIAL_PROFILES[4],
  },
];

export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: 'subj-1',
    code: 'CS501',
    name: 'Data Structures & Algorithms',
    credits: 4,
    course_id: 'course-1',
    semester: 5,
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Robert Vance',
  },
  {
    id: 'subj-2',
    code: 'CS502',
    name: 'React & Modern Frontend Technologies',
    credits: 4,
    course_id: 'course-1',
    semester: 5,
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy',
  },
  {
    id: 'subj-3',
    code: 'CS503',
    name: 'Database Management Systems (DBMS)',
    credits: 4,
    course_id: 'course-1',
    semester: 5,
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Robert Vance',
  },
  {
    id: 'subj-4',
    code: 'CS504',
    name: 'Operating Systems & System Architecture',
    credits: 3,
    course_id: 'course-1',
    semester: 5,
    teacher_id: 'teacher-3',
    teacher_name: 'Dr. Alan Turing',
  },
  {
    id: 'subj-5',
    code: 'CS505',
    name: 'Computer Networks & Security',
    credits: 3,
    course_id: 'course-1',
    semester: 5,
    teacher_id: 'teacher-3',
    teacher_name: 'Dr. Alan Turing',
  },
  {
    id: 'subj-6',
    code: 'AI501',
    name: 'Artificial Intelligence & Machine Learning',
    credits: 4,
    course_id: 'course-3',
    semester: 5,
    teacher_id: 'teacher-3',
    teacher_name: 'Dr. Alan Turing',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // Subject 1 - DSA
  { id: 'att-1', student_id: 'student-1', subject_id: 'subj-1', subject_name: 'Data Structures & Algorithms', subject_code: 'CS501', date: '2026-09-01', status: 'present' },
  { id: 'att-2', student_id: 'student-1', subject_id: 'subj-1', subject_name: 'Data Structures & Algorithms', subject_code: 'CS501', date: '2026-09-02', status: 'present' },
  { id: 'att-3', student_id: 'student-1', subject_id: 'subj-1', subject_name: 'Data Structures & Algorithms', subject_code: 'CS501', date: '2026-09-03', status: 'present' },
  { id: 'att-4', student_id: 'student-1', subject_id: 'subj-1', subject_name: 'Data Structures & Algorithms', subject_code: 'CS501', date: '2026-09-04', status: 'absent' },
  { id: 'att-5', student_id: 'student-1', subject_id: 'subj-1', subject_name: 'Data Structures & Algorithms', subject_code: 'CS501', date: '2026-09-05', status: 'present' },

  // Subject 2 - React Dev
  { id: 'att-6', student_id: 'student-1', subject_id: 'subj-2', subject_name: 'React & Modern Frontend', subject_code: 'CS502', date: '2026-09-01', status: 'present' },
  { id: 'att-7', student_id: 'student-1', subject_id: 'subj-2', subject_name: 'React & Modern Frontend', subject_code: 'CS502', date: '2026-09-02', status: 'present' },
  { id: 'att-8', student_id: 'student-1', subject_id: 'subj-2', subject_name: 'React & Modern Frontend', subject_code: 'CS502', date: '2026-09-03', status: 'present' },
  { id: 'att-9', student_id: 'student-1', subject_id: 'subj-2', subject_name: 'React & Modern Frontend', subject_code: 'CS502', date: '2026-09-04', status: 'present' },

  // Subject 3 - DBMS
  { id: 'att-10', student_id: 'student-1', subject_id: 'subj-3', subject_name: 'Database Management Systems', subject_code: 'CS503', date: '2026-09-01', status: 'present' },
  { id: 'att-11', student_id: 'student-1', subject_id: 'subj-3', subject_name: 'Database Management Systems', subject_code: 'CS503', date: '2026-09-02', status: 'late' },
  { id: 'att-12', student_id: 'student-1', subject_id: 'subj-3', subject_name: 'Database Management Systems', subject_code: 'CS503', date: '2026-09-03', status: 'present' },

  // Subject 4 - OS
  { id: 'att-13', student_id: 'student-1', subject_id: 'subj-4', subject_name: 'Operating Systems', subject_code: 'CS504', date: '2026-09-01', status: 'present' },
  { id: 'att-14', student_id: 'student-1', subject_id: 'subj-4', subject_name: 'Operating Systems', subject_code: 'CS504', date: '2026-09-02', status: 'present' },
  { id: 'att-15', student_id: 'student-1', subject_id: 'subj-4', subject_name: 'Operating Systems', subject_code: 'CS504', date: '2026-09-03', status: 'absent' },
];

export const INITIAL_MARKS: MarkRecord[] = [
  {
    id: 'mark-1',
    student_id: 'student-1',
    subject_id: 'subj-1',
    subject_name: 'Data Structures & Algorithms',
    subject_code: 'CS501',
    semester: 5,
    internal_marks: 18,
    mid_sem_marks: 27,
    assignment_marks: 9,
    practical_marks: 19,
    end_sem_marks: 42,
    total_marks: 91,
    max_marks: 100,
    grade: 'A+',
    sgpa: 9.1,
    cgpa: 8.95,
  },
  {
    id: 'mark-2',
    student_id: 'student-1',
    subject_id: 'subj-2',
    subject_name: 'React & Modern Frontend',
    subject_code: 'CS502',
    semester: 5,
    internal_marks: 19,
    mid_sem_marks: 28,
    assignment_marks: 10,
    practical_marks: 20,
    end_sem_marks: 45,
    total_marks: 95,
    max_marks: 100,
    grade: 'O',
    sgpa: 9.5,
    cgpa: 8.95,
  },
  {
    id: 'mark-3',
    student_id: 'student-1',
    subject_id: 'subj-3',
    subject_name: 'Database Management Systems',
    subject_code: 'CS503',
    semester: 5,
    internal_marks: 16,
    mid_sem_marks: 25,
    assignment_marks: 8,
    practical_marks: 18,
    end_sem_marks: 39,
    total_marks: 84,
    max_marks: 100,
    grade: 'A',
    sgpa: 8.4,
    cgpa: 8.95,
  },
  {
    id: 'mark-4',
    student_id: 'student-1',
    subject_id: 'subj-4',
    subject_name: 'Operating Systems',
    subject_code: 'CS504',
    semester: 5,
    internal_marks: 17,
    mid_sem_marks: 24,
    assignment_marks: 9,
    practical_marks: 17,
    end_sem_marks: 41,
    total_marks: 88,
    max_marks: 100,
    grade: 'A+',
    sgpa: 8.8,
    cgpa: 8.95,
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asgn-1',
    title: 'Balanced Binary Search Tree Implementation',
    subject_id: 'subj-1',
    subject_name: 'Data Structures & Algorithms',
    description: 'Implement an AVL Tree in TypeScript/C++ with insert, delete, and balancing rotations. Include unit tests.',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Robert Vance',
    created_at: '2026-09-01T10:00:00Z',
    due_date: '2026-09-15T23:59:59Z',
    max_marks: 50,
    submission_status: 'submitted',
  },
  {
    id: 'asgn-2',
    title: 'Build a Full-stack React Dashboard',
    subject_id: 'subj-2',
    subject_name: 'React & Modern Frontend',
    description: 'Create an interactive analytics dashboard featuring state management, custom hooks, and Tailwind styling.',
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy',
    created_at: '2026-09-03T11:30:00Z',
    due_date: '2026-09-20T23:59:59Z',
    max_marks: 100,
    submission_status: 'graded',
  },
  {
    id: 'asgn-3',
    title: 'SQL Normalization & Indexing Benchmarks',
    subject_id: 'subj-3',
    subject_name: 'Database Management Systems',
    description: 'Normalize an unnormalized e-commerce schema to 3NF and BCNF. Measure query execution time with B-Tree indexes.',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Robert Vance',
    created_at: '2026-09-05T09:00:00Z',
    due_date: '2026-09-25T23:59:59Z',
    max_marks: 50,
    submission_status: 'pending',
  },
];

export const INITIAL_SUBMISSIONS: AssignmentSubmission[] = [
  {
    id: 'sub-1',
    assignment_id: 'asgn-1',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    roll_number: '21CS001',
    submission_date: '2026-09-05T14:20:00Z',
    file_url: 'https://storage.university.edu/submissions/avl-tree-alex.zip',
    remarks: 'Code is well-structured and passes all AVL rotation tests.',
    status: 'submitted',
  },
  {
    id: 'sub-2',
    assignment_id: 'asgn-2',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    roll_number: '21CS001',
    submission_date: '2026-09-04T18:10:00Z',
    file_url: 'https://storage.university.edu/submissions/react-dashboard-alex.zip',
    remarks: 'Outstanding UI design and smooth Recharts integration!',
    grade: 98,
    status: 'graded',
  },
];

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-1',
    name: 'Mid-Semester Theory Examination',
    subject_id: 'subj-1',
    subject_name: 'Data Structures & Algorithms',
    exam_type: 'mid_sem',
    exam_date: '2026-10-05',
    start_time: '10:00:00',
    end_time: '12:00:00',
    room: 'Hall 302',
    instructions: 'Bring your physical hall ticket and university ID. No electronic gadgets permitted.',
    max_marks: 50,
  },
  {
    id: 'exam-2',
    name: 'React Frontend Development Practical Lab Exam',
    subject_id: 'subj-2',
    subject_name: 'React & Modern Frontend',
    exam_type: 'practical',
    exam_date: '2026-10-08',
    start_time: '14:00:00',
    end_time: '17:00:00',
    room: 'Computer Lab 4B',
    instructions: 'Live coding environment provided. Internet allowed only for React documentation.',
    max_marks: 50,
  },
  {
    id: 'exam-3',
    name: 'DBMS Quiz & Schema Design Assessment',
    subject_id: 'subj-3',
    subject_name: 'Database Management Systems',
    exam_type: 'quiz',
    exam_date: '2026-09-28',
    start_time: '11:00:00',
    end_time: '12:00:00',
    room: 'Hall 105',
    instructions: 'Multiple choice & short SQL query questions on relational algebra.',
    max_marks: 25,
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  { id: 'tt-1', day: 'Monday', start_time: '09:00', end_time: '10:00', subject_id: 'subj-1', subject_name: 'Data Structures', subject_code: 'CS501', teacher_name: 'Dr. Vance', room: '301', type: 'Lecture' },
  { id: 'tt-2', day: 'Monday', start_time: '10:15', end_time: '12:15', subject_id: 'subj-2', subject_name: 'React Dev Lab', subject_code: 'CS502', teacher_name: 'Prof. Reddy', room: 'Lab 4B', type: 'Lab' },
  { id: 'tt-3', day: 'Tuesday', start_time: '09:00', end_time: '10:00', subject_id: 'subj-3', subject_name: 'DBMS', subject_code: 'CS503', teacher_name: 'Dr. Vance', room: '302', type: 'Lecture' },
  { id: 'tt-4', day: 'Tuesday', start_time: '11:00', end_time: '12:00', subject_id: 'subj-4', subject_name: 'Operating Systems', subject_code: 'CS504', teacher_name: 'Dr. Turing', room: '301', type: 'Lecture' },
  { id: 'tt-5', day: 'Wednesday', start_time: '09:00', end_time: '11:00', subject_id: 'subj-1', subject_name: 'DSA Lab', subject_code: 'CS501', teacher_name: 'Dr. Vance', room: 'Lab 2A', type: 'Lab' },
  { id: 'tt-6', day: 'Wednesday', start_time: '11:15', end_time: '12:15', subject_id: 'subj-5', subject_name: 'Computer Networks', subject_code: 'CS505', teacher_name: 'Dr. Turing', room: '302', type: 'Lecture' },
  { id: 'tt-7', day: 'Thursday', start_time: '10:00', end_time: '11:00', subject_id: 'subj-2', subject_name: 'React Dev', subject_code: 'CS502', teacher_name: 'Prof. Reddy', room: '301', type: 'Lecture' },
  { id: 'tt-8', day: 'Friday', start_time: '09:00', end_time: '10:00', subject_id: 'subj-3', subject_name: 'DBMS', subject_code: 'CS503', teacher_name: 'Dr. Vance', room: '302', type: 'Lecture' },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not-1',
    title: 'Annual Campus Hackathon 2026 Registration Open',
    description: 'Join the 36-hour hackathon with cash prizes up to $10,000. Registration closes September 20th. Form your teams now!',
    category: 'Placement',
    priority: 'High',
    publish_date: '2026-09-05',
    expiry_date: '2026-09-20',
    author_name: 'Training & Placement Cell',
    pinned: true,
    archived: false,
  },
  {
    id: 'not-2',
    title: 'Mid-Semester Examination Schedule Announcement',
    description: 'The mid-sem exam datesheet for 5th Semester B.Tech has been finalized. Exams commence from October 5th, 2026.',
    category: 'Exam',
    priority: 'Urgent',
    publish_date: '2026-09-06',
    expiry_date: '2026-10-15',
    author_name: 'Office of Controller of Exams',
    pinned: true,
    archived: false,
  },
  {
    id: 'not-3',
    title: 'Guest Lecture on Cloud Infrastructure & DevOps',
    description: 'Special session by Senior Principal Architect from AWS on September 18th in Auditorium B.',
    category: 'Academic',
    priority: 'Normal',
    publish_date: '2026-09-04',
    expiry_date: '2026-09-18',
    author_name: 'Department of Computer Science',
    pinned: false,
    archived: false,
  },
];

export const INITIAL_EVENTS: CollegeEvent[] = [
  {
    id: 'evt-1',
    title: 'Hackathon 2026: Code for Impact',
    description: '36-hour inter-college coding competition focusing on AI, Web3, and Open Source software.',
    event_type: 'College Event',
    start_date: '2026-09-22T09:00:00Z',
    end_date: '2026-09-23T21:00:00Z',
    location: 'Main University Auditorium',
  },
  {
    id: 'evt-2',
    title: 'React & TypeScript Deep-Dive Workshop',
    description: 'Hands-on training session on modern frontend patterns, state management, and Vite tooling.',
    event_type: 'Workshop',
    start_date: '2026-09-18T14:00:00Z',
    end_date: '2026-09-18T18:00:00Z',
    location: 'Lab 4B',
  },
  {
    id: 'evt-3',
    title: 'National Innovation Holiday',
    description: 'University closed in observance of National Science & Technology Day.',
    event_type: 'Holiday',
    start_date: '2026-10-02T00:00:00Z',
    end_date: '2026-10-02T23:59:59Z',
    location: 'Campus Wide',
  },
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-1',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    name: 'AWS Certified Cloud Practitioner',
    organization: 'Amazon Web Services',
    issue_date: '2026-06-15',
    certificate_code: 'AWS-CCP-884920',
    credential_url: 'https://aws.amazon.com/verification/AWS-CCP-884920',
    category: 'Technical',
    description: 'Validated understanding of AWS Cloud concepts, security, architecture, and billing models.',
    file_url: 'https://images.unsplash.com/photo-1589330694653-aded6fac0243?w=500',
    status: 'verified',
    remarks: 'Verified against AWS Credential Directory.',
  },
  {
    id: 'cert-2',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    name: 'Full-Stack Web Development Immersion',
    organization: 'Meta Developer Certification',
    issue_date: '2026-04-10',
    certificate_code: 'META-DEV-99120',
    credential_url: 'https://coursera.org/verify/META-DEV-99120',
    category: 'Course',
    description: 'Completed 9-course specialization covering HTML, CSS, JavaScript, React, and Django backend.',
    file_url: 'https://images.unsplash.com/photo-1589330694653-aded6fac0243?w=500',
    status: 'verified',
    remarks: 'Official certificate verified by Department.',
  },
  {
    id: 'cert-3',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    name: 'Summer Software Engineering Internship',
    organization: 'TechCorp Solutions',
    issue_date: '2026-08-01',
    certificate_code: 'TC-INT-2026-04',
    credential_url: 'https://techcorp.io/verify/TC-INT-2026-04',
    category: 'Internship',
    description: '8-week internship as Frontend Engineering Intern working on React micro-frontends.',
    file_url: 'https://images.unsplash.com/photo-1589330694653-aded6fac0243?w=500',
    status: 'pending',
    remarks: 'Awaiting admin document audit.',
  },
];

export const INITIAL_RESUME: ResumeData = {
  id: 'res-1',
  student_id: 'student-1',
  full_name: 'Alex Johnson',
  email: 'student@university.edu',
  phone: '+1 (555) 019-2834',
  location: 'San Francisco, CA',
  linkedin: 'https://linkedin.com/in/alexjohnson-dev',
  github: 'https://github.com/alexjohnson',
  portfolio: 'https://alexjohnson.dev',
  summary: 'Passionate Computer Science student and Frontend Developer with expertise in React, TypeScript, Tailwind CSS, and cloud architecture. Experienced in building responsive web applications and RESTful backend APIs.',
  template_id: 'modern',
  education: [
    {
      id: 'edu-1',
      degree: 'B.Tech in Computer Science & Engineering',
      university: 'State Technological University',
      course: 'Computer Science',
      start_year: '2023',
      end_year: '2027',
      grade: 'CGPA: 8.95 / 10.0',
    },
  ],
  skills: [
    { id: 'sk-1', category: 'Frontend', items: ['HTML5', 'CSS3', 'JavaScript', 'TypeScript', 'React.js', 'Tailwind CSS', 'Redux'] },
    { id: 'sk-2', category: 'Backend & DB', items: ['Node.js', 'Express.js', 'Supabase', 'PostgreSQL', 'REST APIs'] },
    { id: 'sk-3', category: 'Tools & Cloud', items: ['Git', 'GitHub', 'AWS (CCP)', 'Vite', 'VS Code', 'Postman'] },
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'Smart Student Management & Career Portal',
      description: 'Built a multi-portal SaaS system with role-based routing, real-time attendance analytics, jsPDF resume builder, and rule-based AI career roadmapping.',
      technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Supabase', 'Recharts'],
      github_link: 'https://github.com/alexjohnson/student-portal',
      demo_link: 'https://student-portal-demo.vercel.app',
    },
    {
      id: 'proj-2',
      name: 'E-Commerce Real-time Analytics Dashboard',
      description: 'Engineered a high-performance web dashboard featuring live chart visualizations, order filtering, and mock payment checkout integration.',
      technologies: ['React', 'TypeScript', 'Recharts', 'Tailwind CSS'],
      github_link: 'https://github.com/alexjohnson/analytics-dash',
    },
  ],
  internships: [
    {
      id: 'exp-1',
      organization: 'TechCorp Solutions',
      role: 'Frontend Engineering Intern',
      duration: 'June 2026 - August 2026',
      description: 'Optimized React component render performance by 35%. Collaborated with UX team to convert Figma designs into pixel-perfect responsive templates.',
      technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Git'],
    },
  ],
  certificates: [
    {
      id: 'cert-r-1',
      name: 'AWS Certified Cloud Practitioner',
      organization: 'Amazon Web Services',
      date: 'June 2026',
      credential_url: 'https://aws.amazon.com/verification',
    },
    {
      id: 'cert-r-2',
      name: 'Meta Full-Stack Web Developer Specialization',
      organization: 'Meta',
      date: 'April 2026',
    },
  ],
  achievements: [
    'Winner of Regional University Hackathon 2025 (1st Place out of 45 teams)',
    'Dean’s Honor Roll List for top academic performance in Semester 4',
  ],
  languages: ['English (Fluent)', 'Spanish (Intermediate)'],
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'user-student-1',
    title: 'Assignment Deadline Reminder',
    message: 'Balanced Binary Search Tree Implementation is due on Sept 15.',
    type: 'assignment',
    is_read: false,
    created_at: '2026-09-06T08:00:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'user-student-1',
    title: 'Certificate Verified',
    message: 'Your AWS Certified Cloud Practitioner certificate has been approved by admin.',
    type: 'certificate',
    is_read: true,
    created_at: '2026-09-05T14:30:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'user-student-1',
    title: 'New Exam Scheduled',
    message: 'React Development Lab Exam has been scheduled for Oct 8.',
    type: 'exam',
    is_read: false,
    created_at: '2026-09-04T11:15:00Z',
  },
];
