import {
  UserProfile,
  Student,
  Teacher,
  Course,
  Subject,
  TeacherSubject,
  StudentSubject,
  AttendanceRecord,
  MarkRecord,
  Assignment,
  AssignmentSubmission,
  Exam,
  TimetableSlot,
  Notice,
  CollegeEvent,
  Certificate,
  ResumeData,
  NotificationItem,
  FeeRecord,
  HODInfo,
} from '../types';

export const INITIAL_PROFILES: UserProfile[] = [
  // Student Accounts (10)
  {
    id: 'user-student-1',
    full_name: 'Alex Johnson',
    email: 'student1@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    phone: '+1 555-0401',
    gender: 'Male',
    dob: '2003-05-14',
    address: '42 University Heights, Campus Town',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-2',
    full_name: 'Priya Sharma',
    email: 'priya.sharma@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    phone: '+1 555-0402',
    gender: 'Female',
    dob: '2003-11-20',
    address: '18 Tech Hostel, North Campus',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-3',
    full_name: 'Rahul Patel',
    email: 'rahul.patel@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    phone: '+1 555-0403',
    gender: 'Male',
    dob: '2002-09-03',
    address: '77 Student Row, West Campus',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-4',
    full_name: 'Ananya Gupta',
    email: 'ananya.gupta@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    phone: '+1 555-0404',
    gender: 'Female',
    dob: '2003-02-18',
    address: '21 East Hostel, Campus South',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-5',
    full_name: 'Rohan Verma',
    email: 'rohan.verma@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    phone: '+1 555-0405',
    gender: 'Male',
    dob: '2003-07-25',
    address: '12 University Enclave',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-6',
    full_name: 'Sneha Rao',
    email: 'sneha.rao@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    phone: '+1 555-0406',
    gender: 'Female',
    dob: '2003-10-12',
    address: '45 Green Park, Campus West',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-7',
    full_name: 'Vikram Singh',
    email: 'vikram.singh@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    phone: '+1 555-0407',
    gender: 'Male',
    dob: '2002-12-05',
    address: '88 Scholars Lane',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-8',
    full_name: 'Neha Kulkarni',
    email: 'neha.kulkarni@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
    phone: '+1 555-0408',
    gender: 'Female',
    dob: '2003-04-30',
    address: '09 Science Hostel',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-9',
    full_name: 'Arjun Nair',
    email: 'arjun.nair@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    phone: '+1 555-0409',
    gender: 'Male',
    dob: '2003-08-14',
    address: '33 Tech Enclave',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-10',
    full_name: 'Kavya Joshi',
    email: 'kavya.joshi@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    phone: '+1 555-0410',
    gender: 'Female',
    dob: '2003-01-22',
    address: '55 Campus View Apartments',
    created_at: '2023-08-15T00:00:00Z',
  },

  // Teacher Accounts (10)
  {
    id: 'user-teacher-1',
    full_name: 'Dr. Vance (C++ Instructor)',
    email: 'teacher1@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    phone: '+1 555-0301',
    gender: 'Male',
    dob: '1980-04-12',
    address: 'Faculty Quarters A-12',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-teacher-2',
    full_name: 'Prof. Meera Reddy (Mathematics)',
    email: 'teacher2@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    phone: '+1 555-0302',
    gender: 'Female',
    dob: '1985-08-23',
    address: 'Faculty Quarters B-04',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-teacher-3',
    full_name: 'Dr. Alan Turing (DBMS Specialist)',
    email: 'teacher3@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    phone: '+1 555-0303',
    gender: 'Male',
    dob: '1982-06-23',
    address: 'Faculty Quarters C-01',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-teacher-4',
    full_name: 'Prof. Grace Hopper (OS Instructor)',
    email: 'teacher4@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    phone: '+1 555-0304',
    gender: 'Female',
    dob: '1984-12-09',
    address: 'Faculty Quarters A-05',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-teacher-5',
    full_name: 'Dr. Ken Thompson (Systems)',
    email: 'teacher5@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    phone: '+1 555-0305',
    gender: 'Male',
    dob: '1981-02-04',
    address: 'Faculty Quarters D-11',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-teacher-6',
    full_name: 'Prof. Barbara Liskov (Software Eng)',
    email: 'teacher6@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    phone: '+1 555-0306',
    gender: 'Female',
    dob: '1983-11-07',
    address: 'Faculty Quarters B-09',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-teacher-7',
    full_name: 'Dr. Donald Knuth (Algorithms)',
    email: 'teacher7@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    phone: '+1 555-0307',
    gender: 'Male',
    dob: '1979-01-10',
    address: 'Faculty Quarters A-01',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-teacher-8',
    full_name: 'Prof. Tim Berners-Lee (Web Tech)',
    email: 'teacher8@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    phone: '+1 555-0308',
    gender: 'Male',
    dob: '1986-06-08',
    address: 'Faculty Quarters C-07',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-teacher-9',
    full_name: 'Dr. Ada Lovelace (Data Structures)',
    email: 'teacher9@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    phone: '+1 555-0309',
    gender: 'Female',
    dob: '1987-12-10',
    address: 'Faculty Quarters B-02',
    created_at: '2021-06-10T00:00:00Z',
  },
  {
    id: 'user-teacher-10',
    full_name: 'Prof. Claude Shannon (Networks)',
    email: 'teacher10@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    phone: '+1 555-0310',
    gender: 'Male',
    dob: '1982-04-30',
    address: 'Faculty Quarters D-03',
    created_at: '2021-06-10T00:00:00Z',
  },

  // HOD Accounts (2)
  {
    id: 'user-hod-1',
    full_name: 'Dr. Robert Carter (HOD - Computer Science)',
    email: 'hod.cs@college.com',
    role: 'hod',
    avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150',
    phone: '+1 555-0200',
    gender: 'Male',
    dob: '1978-03-15',
    address: 'CS Department Block B, Room 204',
    created_at: '2020-01-01T00:00:00Z',
  },
  {
    id: 'user-hod-2',
    full_name: 'Dr. Sarah Jenkins (HOD - IT)',
    email: 'hod.it@college.com',
    role: 'hod',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    phone: '+1 555-0201',
    gender: 'Female',
    dob: '1980-07-19',
    address: 'IT Department Block A, Room 102',
    created_at: '2020-01-01T00:00:00Z',
  },

  // Admin Accounts (2)
  {
    id: 'user-admin-1',
    full_name: 'Dr. Eleanor Vance (Institutional Admin)',
    email: 'admin@college.com',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    phone: '+1 555-0100',
    gender: 'Female',
    dob: '1975-01-05',
    address: 'Administration Block Room 101',
    created_at: '2020-01-01T00:00:00Z',
  },
  {
    id: 'user-admin-2',
    full_name: 'Prof. Marcus Thorne (System Admin)',
    email: 'admin2@college.com',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    phone: '+1 555-0101',
    gender: 'Male',
    dob: '1978-08-22',
    address: 'IT Infrastructure Suite, Room 102',
    created_at: '2020-01-01T00:00:00Z',
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-1',
    code: 'CSE-BTECH',
    name: 'B.Tech in Computer Science & Engineering',
    department: 'Computer Science',
    description: '4-Year undergraduate program focusing on algorithms, system design, and web software engineering.',
    duration_years: 4,
    total_semesters: 8,
    active: true,
    student_count: 140,
  },
  {
    id: 'course-2',
    code: 'IT-BTECH',
    name: 'B.Tech in Information Technology',
    department: 'Information Technology',
    description: 'Comprehensive IT degree program focusing on software architecture, cloud platforms, and security.',
    duration_years: 4,
    total_semesters: 8,
    active: true,
    student_count: 110,
  },
];

export const INITIAL_TEACHERS: Teacher[] = [
  { id: 'teacher-1', profile_id: 'user-teacher-1', teacher_id_code: 'TCH-1001', department: 'Computer Science', designation: 'Associate Professor', profile: INITIAL_PROFILES[10] },
  { id: 'teacher-2', profile_id: 'user-teacher-2', teacher_id_code: 'TCH-1002', department: 'Computer Science', designation: 'Assistant Professor', profile: INITIAL_PROFILES[11] },
  { id: 'teacher-3', profile_id: 'user-teacher-3', teacher_id_code: 'TCH-1003', department: 'Computer Science', designation: 'Professor', profile: INITIAL_PROFILES[12] },
  { id: 'teacher-4', profile_id: 'user-teacher-4', teacher_id_code: 'TCH-1004', department: 'Computer Science', designation: 'Assistant Professor', profile: INITIAL_PROFILES[13] },
  { id: 'teacher-5', profile_id: 'user-teacher-5', teacher_id_code: 'TCH-1005', department: 'Computer Science', designation: 'Senior Lecturer', profile: INITIAL_PROFILES[14] },
  { id: 'teacher-6', profile_id: 'user-teacher-6', teacher_id_code: 'TCH-1006', department: 'Information Technology', designation: 'Associate Professor', profile: INITIAL_PROFILES[15] },
  { id: 'teacher-7', profile_id: 'user-teacher-7', teacher_id_code: 'TCH-1007', department: 'Information Technology', designation: 'Professor', profile: INITIAL_PROFILES[16] },
  { id: 'teacher-8', profile_id: 'user-teacher-8', teacher_id_code: 'TCH-1008', department: 'Information Technology', designation: 'Assistant Professor', profile: INITIAL_PROFILES[17] },
  { id: 'teacher-9', profile_id: 'user-teacher-9', teacher_id_code: 'TCH-1009', department: 'Electronics', designation: 'Assistant Professor', profile: INITIAL_PROFILES[18] },
  { id: 'teacher-10', profile_id: 'user-teacher-10', teacher_id_code: 'TCH-1010', department: 'Electronics', designation: 'Senior Lecturer', profile: INITIAL_PROFILES[19] },
];

export const INITIAL_STUDENTS: Student[] = [
  { id: 'student-1', profile_id: 'user-student-1', student_id_code: 'STD-1001', course_id: 'course-1', course_name: 'B.Tech CSE', department: 'Computer Science', branch: 'CSE', semester: 5, section: 'A', roll_number: '23CS101', admission_year: 2023, guardian_name: 'Robert Johnson Sr.', guardian_phone: '+1 555-9081', guardian_relation: 'Father', profile: INITIAL_PROFILES[0] },
  { id: 'student-2', profile_id: 'user-student-2', student_id_code: 'STD-1002', course_id: 'course-1', course_name: 'B.Tech CSE', department: 'Computer Science', branch: 'CSE', semester: 5, section: 'A', roll_number: '23CS102', admission_year: 2023, guardian_name: 'Sunil Sharma', guardian_phone: '+1 555-9082', guardian_relation: 'Father', profile: INITIAL_PROFILES[1] },
  { id: 'student-3', profile_id: 'user-student-3', student_id_code: 'STD-1003', course_id: 'course-1', course_name: 'B.Tech CSE', department: 'Computer Science', branch: 'CSE', semester: 5, section: 'A', roll_number: '23CS103', admission_year: 2023, guardian_name: 'Mahesh Patel', guardian_phone: '+1 555-9083', guardian_relation: 'Father', profile: INITIAL_PROFILES[2] },
  { id: 'student-4', profile_id: 'user-student-4', student_id_code: 'STD-1004', course_id: 'course-1', course_name: 'B.Tech CSE', department: 'Computer Science', branch: 'CSE', semester: 5, section: 'B', roll_number: '23CS104', admission_year: 2023, guardian_name: 'Alok Gupta', guardian_phone: '+1 555-9084', guardian_relation: 'Father', profile: INITIAL_PROFILES[3] },
  { id: 'student-5', profile_id: 'user-student-5', student_id_code: 'STD-1005', course_id: 'course-1', course_name: 'B.Tech CSE', department: 'Computer Science', branch: 'CSE', semester: 5, section: 'B', roll_number: '23CS105', admission_year: 2023, guardian_name: 'Vikas Verma', guardian_phone: '+1 555-9085', guardian_relation: 'Father', profile: INITIAL_PROFILES[4] },
  { id: 'student-6', profile_id: 'user-student-6', student_id_code: 'STD-1006', course_id: 'course-2', course_name: 'B.Tech IT', department: 'Information Technology', branch: 'IT', semester: 5, section: 'A', roll_number: '23IT101', admission_year: 2023, guardian_name: 'K. Rao', guardian_phone: '+1 555-9086', guardian_relation: 'Father', profile: INITIAL_PROFILES[5] },
  { id: 'student-7', profile_id: 'user-student-7', student_id_code: 'STD-1007', course_id: 'course-2', course_name: 'B.Tech IT', department: 'Information Technology', branch: 'IT', semester: 5, section: 'A', roll_number: '23IT102', admission_year: 2023, guardian_name: 'D. Singh', guardian_phone: '+1 555-9087', guardian_relation: 'Father', profile: INITIAL_PROFILES[6] },
  { id: 'student-8', profile_id: 'user-student-8', student_id_code: 'STD-1008', course_id: 'course-2', course_name: 'B.Tech IT', department: 'Information Technology', branch: 'IT', semester: 5, section: 'B', roll_number: '23IT103', admission_year: 2023, guardian_name: 'S. Kulkarni', guardian_phone: '+1 555-9088', guardian_relation: 'Father', profile: INITIAL_PROFILES[7] },
  { id: 'student-9', profile_id: 'user-student-9', student_id_code: 'STD-1009', course_id: 'course-1', course_name: 'B.Tech ECE', department: 'Electronics', branch: 'ECE', semester: 5, section: 'A', roll_number: '23ECE101', admission_year: 2023, guardian_name: 'M. Nair', guardian_phone: '+1 555-9089', guardian_relation: 'Father', profile: INITIAL_PROFILES[8] },
  { id: 'student-10', profile_id: 'user-student-10', student_id_code: 'STD-1010', course_id: 'course-1', course_name: 'B.Tech ECE', department: 'Electronics', branch: 'ECE', semester: 5, section: 'A', roll_number: '23ECE102', admission_year: 2023, guardian_name: 'R. Joshi', guardian_phone: '+1 555-9090', guardian_relation: 'Father', profile: INITIAL_PROFILES[9] },
];

export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: 'subj-cpp',
    code: 'CS501',
    name: 'C++ & Object-Oriented Programming',
    credits: 4,
    course_id: 'course-1',
    semester: 5,
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
  },
  {
    id: 'subj-math',
    code: 'MA502',
    name: 'Discrete Mathematics & Linear Algebra',
    credits: 4,
    course_id: 'course-1',
    semester: 5,
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy (teacher2@college.com)',
  },
  {
    id: 'subj-web',
    code: 'CS503',
    name: 'React & Modern Web Development',
    credits: 4,
    course_id: 'course-1',
    semester: 5,
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
  },
];

// Requirement 4 & 10: Teacher Subject Allocations
export const INITIAL_TEACHER_SUBJECTS: TeacherSubject[] = [
  // Teacher 1 (teacher1@college.com) -> C++ (subj-cpp) and Web Dev (subj-web)
  { id: 'ts-1', teacher_id: 'teacher-1', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501' },
  { id: 'ts-2', teacher_id: 'teacher-1', subject_id: 'subj-web', subject_name: 'React & Web Dev', subject_code: 'CS503' },

  // Teacher 2 (teacher2@college.com) -> Mathematics (subj-math) ONLY
  { id: 'ts-3', teacher_id: 'teacher-2', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502' },
];

// Student Subject Enrollments
export const INITIAL_STUDENT_SUBJECTS: StudentSubject[] = [
  { id: 'ss-1', student_id: 'student-1', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501' },
  { id: 'ss-2', student_id: 'student-1', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502' },
  { id: 'ss-3', student_id: 'student-1', subject_id: 'subj-web', subject_name: 'React & Web Dev', subject_code: 'CS503' },
  { id: 'ss-4', student_id: 'student-2', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501' },
  { id: 'ss-5', student_id: 'student-2', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502' },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // C++ Attendance (Taught by Teacher 1)
  { id: 'att-1', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501', teacher_id: 'teacher-1', date: '2026-09-01', status: 'present', marked_by: 'teacher-1' },
  { id: 'att-2', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501', teacher_id: 'teacher-1', date: '2026-09-02', status: 'present', marked_by: 'teacher-1' },
  { id: 'att-3', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501', teacher_id: 'teacher-1', date: '2026-09-03', status: 'absent', marked_by: 'teacher-1' },

  // Mathematics Attendance (Taught by Teacher 2)
  { id: 'att-4', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502', teacher_id: 'teacher-2', date: '2026-09-01', status: 'present', marked_by: 'teacher-2' },
  { id: 'att-5', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502', teacher_id: 'teacher-2', date: '2026-09-02', status: 'present', marked_by: 'teacher-2' },
  { id: 'att-6', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502', teacher_id: 'teacher-2', date: '2026-09-03', status: 'present', marked_by: 'teacher-2' },
];

export const INITIAL_MARKS: MarkRecord[] = [
  // C++ Marks (Teacher 1)
  {
    id: 'mark-1',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    roll_number: '21CS001',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    teacher_id: 'teacher-1',
    assessment_type: 'End Semester',
    semester: 5,
    internal_marks: 18,
    mid_sem_marks: 27,
    assignment_marks: 9,
    practical_marks: 19,
    end_sem_marks: 42,
    total_marks: 91,
    max_marks: 100,
    grade: 'A+',
    sgpa: 9.1,
    cgpa: 8.95,
  },
  // Mathematics Marks (Teacher 2)
  {
    id: 'mark-2',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    roll_number: '21CS001',
    subject_id: 'subj-math',
    subject_name: 'Discrete Mathematics',
    subject_code: 'MA502',
    teacher_id: 'teacher-2',
    assessment_type: 'End Semester',
    semester: 5,
    internal_marks: 19,
    mid_sem_marks: 28,
    assignment_marks: 10,
    practical_marks: 18,
    end_sem_marks: 43,
    total_marks: 94,
    max_marks: 100,
    grade: 'O',
    sgpa: 9.4,
    cgpa: 8.95,
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  // C++ Assignment (Teacher 1)
  {
    id: 'asgn-1',
    title: 'C++ Polymorphism & Memory Management',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    course_id: 'course-1',
    semester: 5,
    description: 'Implement a custom smart pointer class in C++ with reference counting and destructor cleanup.',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    created_at: '2026-09-01T10:00:00Z',
    due_date: '2026-09-15T23:59:59Z',
    max_marks: 50,
    submission_status: 'submitted',
  },
  // Mathematics Assignment (Teacher 2)
  {
    id: 'asgn-2',
    title: 'Graph Theory & Matrix Representation',
    subject_id: 'subj-math',
    subject_name: 'Discrete Mathematics',
    subject_code: 'MA502',
    course_id: 'course-1',
    semester: 5,
    description: 'Solve adjacency matrix problems and prove Euler path theorems for connected graphs.',
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy (teacher2@college.com)',
    created_at: '2026-09-03T11:30:00Z',
    due_date: '2026-09-20T23:59:59Z',
    max_marks: 100,
    submission_status: 'graded',
  },
];

export const INITIAL_SUBMISSIONS: AssignmentSubmission[] = [
  {
    id: 'sub-1',
    assignment_id: 'asgn-1',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    roll_number: '21CS001',
    submission_date: '2026-09-05T14:20:00Z',
    file_url: 'https://storage.university.edu/submissions/cpp-smart-pointer.cpp',
    remarks: 'Excellent RAII design pattern implementation!',
    grade: 48,
    status: 'graded',
  },
  {
    id: 'sub-2',
    assignment_id: 'asgn-2',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    roll_number: '21CS001',
    submission_date: '2026-09-04T18:10:00Z',
    file_url: 'https://storage.university.edu/submissions/graph-theory.pdf',
    remarks: 'Flawless mathematical proof of Eulerian graphs.',
    grade: 96,
    status: 'graded',
  },
];

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-1',
    name: 'C++ Object-Oriented Practical Examination',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    teacher_id: 'teacher-1',
    exam_type: 'practical',
    exam_date: '2026-10-05',
    start_time: '10:00:00',
    end_time: '12:00:00',
    duration: '2 Hours',
    room: 'Lab 4B',
    instructions: 'Live C++ coding test. Compile with g++ -std=c++20.',
    max_marks: 50,
  },
  {
    id: 'exam-2',
    name: 'Discrete Mathematics Mid-Semester Written Exam',
    subject_id: 'subj-math',
    subject_name: 'Discrete Mathematics',
    teacher_id: 'teacher-2',
    exam_type: 'mid_sem',
    exam_date: '2026-10-08',
    start_time: '14:00:00',
    end_time: '17:00:00',
    duration: '3 Hours',
    room: 'Hall 302',
    instructions: 'Calculators permitted. Show detailed steps for all proof questions.',
    max_marks: 50,
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  // B.Tech CSE, Semester 5, Section A
  {
    id: 'tt-1',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Monday',
    start_time: '09:00',
    end_time: '10:00',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Lab 4B',
    type: 'Lab',
    status: 'Published',
  },
  {
    id: 'tt-2',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Monday',
    start_time: '10:15',
    end_time: '11:15',
    subject_id: 'subj-math',
    subject_name: 'Discrete Math',
    subject_code: 'MA502',
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy (teacher2@college.com)',
    room: 'Hall 302',
    type: 'Lecture',
    status: 'Published',
  },
  {
    id: 'tt-3',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Tuesday',
    start_time: '09:00',
    end_time: '10:00',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Room 301',
    type: 'Lecture',
    status: 'Published',
  },
  {
    id: 'tt-4',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Tuesday',
    start_time: '11:30',
    end_time: '12:30',
    subject_id: 'subj-web',
    subject_name: 'React & Web Dev',
    subject_code: 'CS503',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Lab 2',
    type: 'Practical',
    status: 'Published',
  },
  {
    id: 'tt-5',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Wednesday',
    start_time: '10:00',
    end_time: '11:00',
    subject_id: 'subj-math',
    subject_name: 'Discrete Math',
    subject_code: 'MA502',
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy (teacher2@college.com)',
    room: 'Room 204',
    type: 'Lecture',
    status: 'Published',
  },
  {
    id: 'tt-6',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Thursday',
    start_time: '09:00',
    end_time: '10:00',
    subject_id: 'subj-web',
    subject_name: 'React & Web Dev',
    subject_code: 'CS503',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Lab 4B',
    type: 'Lab',
    status: 'Published',
  },
  {
    id: 'tt-7',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Friday',
    start_time: '10:00',
    end_time: '11:00',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Room 301',
    type: 'Lecture',
    status: 'Published',
  },

  // B.Tech CSE, Semester 5, Section B
  {
    id: 'tt-8',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'B',
    day: 'Monday',
    start_time: '11:30',
    end_time: '12:30',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Lab 4B',
    type: 'Lab',
    status: 'Published',
  },
  {
    id: 'tt-9',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'B',
    day: 'Tuesday',
    start_time: '10:15',
    end_time: '11:15',
    subject_id: 'subj-math',
    subject_name: 'Discrete Math',
    subject_code: 'MA502',
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy (teacher2@college.com)',
    room: 'Hall 302',
    type: 'Lecture',
    status: 'Published',
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not-1',
    title: 'Mid-Semester Examination Schedule Released',
    description: 'The finalized mid-semester exam datesheet for CS & IT departments has been published by HOD Office. Examinations commence on Oct 1, 2026.',
    category: 'Exam',
    priority: 'Urgent',
    publish_date: '2026-09-06',
    expiry_date: '2026-10-15',
    author_name: 'Dr. Robert Carter (HOD CS)',
    pinned: true,
    archived: false,
  },
  {
    id: 'not-2',
    title: 'Annual Campus Placement Drive 2026 Registration',
    description: 'Top technology companies including Microsoft, Google, and Amazon are visiting campus for 2027 batch recruitment. Register your updated resume before Sept 25.',
    category: 'Placement',
    priority: 'High',
    publish_date: '2026-09-08',
    expiry_date: '2026-09-25',
    author_name: 'Placement & Training Cell',
    pinned: true,
    archived: false,
  },
  {
    id: 'not-3',
    title: 'Special Industry Seminar: AI & Cloud Systems Architecture',
    description: 'Guest speaker session by Senior Cloud Architect from AWS on modern distributed systems and container orchestration.',
    category: 'Academic',
    priority: 'Normal',
    publish_date: '2026-09-09',
    expiry_date: '2026-09-22',
    author_name: 'Department of Computer Science',
    pinned: false,
    archived: false,
  },
  {
    id: 'not-4',
    title: 'Library Clearance & Fee Settlement Notice',
    description: 'All 5th and 7th-semester students are instructed to clear overdue library books and tuition balances prior to hall ticket issuance.',
    category: 'General',
    priority: 'Normal',
    publish_date: '2026-09-05',
    expiry_date: '2026-09-30',
    author_name: 'Admin Finance Office',
    pinned: false,
    archived: false,
  },
];

export const INITIAL_EVENTS: CollegeEvent[] = [
  {
    id: 'evt-1',
    title: 'National Technology Conference 2026',
    description: 'Keynote sessions on modern software engineering, AI, and cloud architectures.',
    event_type: 'College Event',
    start_date: '2026-09-22T09:00:00Z',
    end_date: '2026-09-23T21:00:00Z',
    location: 'Main Campus Auditorium',
  },
  {
    id: 'evt-2',
    title: 'Hackathon 2026: Smart Campus Innovation',
    description: '24-hour coding competition with cash prizes for top full-stack web and mobile apps.',
    event_type: 'Workshop',
    start_date: '2026-10-05T09:00:00Z',
    end_date: '2026-10-06T12:00:00Z',
    location: 'Computer Center Lab 4B',
  },
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-1',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    name: 'AWS Certified Cloud Practitioner',
    organization: 'Amazon Web Services',
    issue_date: '2026-06-15',
    certificate_code: 'AWS-CCP-884920',
    credential_url: 'https://aws.amazon.com/verification',
    category: 'Technical',
    description: 'Validated AWS Cloud security, core architecture, and deployment.',
    file_url: 'https://images.unsplash.com/photo-1589330694653-aded6fac0243?w=500',
    status: 'verified',
    remarks: 'Verified by Admin (Dr. Eleanor Vance).',
  },
  {
    id: 'cert-2',
    student_id: 'student-2',
    student_name: 'Priya Sharma',
    name: 'Meta Front-End Developer Professional Certificate',
    organization: 'Coursera / Meta',
    issue_date: '2026-07-20',
    certificate_code: 'META-FE-9921',
    credential_url: 'https://coursera.org/verify',
    category: 'Course',
    description: 'Mastery of React, JavaScript, HTML/CSS, and UX design principles.',
    file_url: 'https://images.unsplash.com/photo-1589330694653-aded6fac0243?w=500',
    status: 'verified',
    remarks: 'Verified by HOD Dr. Robert Carter.',
  },
];

export const INITIAL_RESUME: ResumeData = {
  id: 'res-1',
  student_id: 'student-1',
  full_name: 'Alex Johnson',
  email: 'student1@college.com',
  phone: '+1 (555) 019-2834',
  location: 'San Francisco, CA',
  linkedin: 'https://linkedin.com/in/alexjohnson-dev',
  github: 'https://github.com/alexjohnson',
  portfolio: 'https://alexjohnson.dev',
  summary: 'Computer Science student skilled in C++, React, TypeScript, and Data Structures. Passionate about software architecture and full-stack web systems.',
  template_id: 'modern',
  education: [
    {
      id: 'edu-1',
      degree: 'B.Tech in Computer Science & Engineering',
      university: 'State Technological University',
      course: 'Computer Science',
      start_year: '2023',
      end_year: '2027',
      grade: 'CGPA: 8.95 / 10.0',
    },
  ],
  skills: [
    { id: 'sk-1', category: 'Languages', items: ['C++', 'JavaScript', 'TypeScript', 'SQL', 'HTML/CSS'] },
    { id: 'sk-2', category: 'Frameworks', items: ['React.js', 'Tailwind CSS', 'Node.js', 'Supabase'] },
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'Smart Student Management System',
      description: 'Built a full role-based portal with Supabase integration, attendance tracking, and AI career guidance.',
      technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Supabase'],
    },
  ],
  internships: [],
  certificates: [
    {
      id: 'cert-r-1',
      name: 'AWS Certified Cloud Practitioner',
      organization: 'Amazon Web Services',
      date: 'June 2026',
    },
  ],
  achievements: ['Dean’s Honor List for 5th Semester'],
  languages: ['English'],
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  // Student Notifications
  {
    id: 'notif-1',
    user_id: 'user-student-1',
    title: 'New Assignment Published in C++',
    message: 'Dr. Vance published C++ Object-Oriented Polymorphism assignment.',
    type: 'assignment',
    is_read: false,
    created_at: '2026-09-06T08:00:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'user-student-1',
    title: 'Mid-Sem Exam Schedule Released',
    message: 'Mid-Semester exams begin Oct 1. Check your timetable desk.',
    type: 'exam',
    is_read: false,
    created_at: '2026-09-08T10:30:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'user-student-1',
    title: 'AWS Certificate Verified',
    message: 'Your AWS Cloud Practitioner certificate was verified by HOD Office.',
    type: 'certificate',
    is_read: true,
    created_at: '2026-09-09T14:15:00Z',
  },

  // Teacher Notifications
  {
    id: 'notif-4',
    user_id: 'user-teacher-1',
    title: 'Attendance Submission Deadline',
    message: 'Please complete attendance marking for C++ Programming Section A before Friday 5:00 PM.',
    type: 'attendance',
    is_read: false,
    created_at: '2026-09-09T09:00:00Z',
  },
  {
    id: 'notif-5',
    user_id: 'user-teacher-1',
    title: 'Gradebook Review Required',
    message: 'HOD Office requested internal marks submission for B.Tech CSE 5th Semester.',
    type: 'result',
    is_read: false,
    created_at: '2026-09-10T11:00:00Z',
  },

  // HOD Notifications
  {
    id: 'notif-6',
    user_id: 'user-hod-1',
    title: 'Department Performance Audit Report Ready',
    message: 'Academic summary and attendance analytics report generated for CS Department.',
    type: 'notice',
    is_read: false,
    created_at: '2026-09-10T08:00:00Z',
  },
  {
    id: 'notif-7',
    user_id: 'user-hod-1',
    title: 'New Student Certificates Pending Verification',
    message: '3 student achievement certificates require departmental verification.',
    type: 'certificate',
    is_read: false,
    created_at: '2026-09-09T16:45:00Z',
  },

  // Admin Notifications
  {
    id: 'notif-8',
    user_id: 'user-admin-1',
    title: 'System Database Backup Successful',
    message: 'PostgreSQL database snapshot & Supabase synchronization completed.',
    type: 'info',
    is_read: false,
    created_at: '2026-09-10T04:00:00Z',
  },
  {
    id: 'notif-9',
    user_id: 'user-admin-1',
    title: 'New Faculty Account Provisioned',
    message: 'Prof. Meera Reddy registered and assigned to Discrete Mathematics.',
    type: 'notice',
    is_read: true,
    created_at: '2026-09-07T12:00:00Z',
  },
];

export const INITIAL_HODS: HODInfo[] = [
  {
    id: 'hod-1',
    profile_id: 'user-hod-1',
    hod_id_code: 'HOD-CS-001',
    department: 'Computer Science',
    profile: INITIAL_PROFILES.find(p => p.id === 'user-hod-1'),
  },
  {
    id: 'hod-2',
    profile_id: 'user-hod-2',
    hod_id_code: 'HOD-IT-001',
    department: 'Information Technology',
    profile: INITIAL_PROFILES.find(p => p.id === 'user-hod-2'),
  },
];

export const INITIAL_FEES: FeeRecord[] = [
  {
    id: 'fee-1',
    student_id: 'student-1',
    student_name: 'Alex Johnson (Student 1)',
    roll_number: '23CS101',
    department: 'Computer Science',
    semester: 5,
    academic_year: '2025-2026',
    tuition_fee: 45000,
    exam_fee: 3500,
    library_fee: 1500,
    total_amount: 50000,
    paid_amount: 50000,
    status: 'paid',
    due_date: '2026-08-30',
    receipt_no: 'REC-2026-08912',
    paid_at: '2026-08-15T10:30:00Z',
  },
  {
    id: 'fee-2',
    student_id: 'student-2',
    student_name: 'Priya Sharma',
    roll_number: '23CS102',
    department: 'Computer Science',
    semester: 5,
    academic_year: '2025-2026',
    tuition_fee: 45000,
    exam_fee: 3500,
    library_fee: 1500,
    total_amount: 50000,
    paid_amount: 25000,
    status: 'partial',
    due_date: '2026-09-30',
  },
  {
    id: 'fee-3',
    student_id: 'student-3',
    student_name: 'Rahul Patel',
    roll_number: '23CS103',
    department: 'Computer Science',
    semester: 5,
    academic_year: '2025-2026',
    tuition_fee: 45000,
    exam_fee: 3500,
    library_fee: 1500,
    total_amount: 50000,
    paid_amount: 0,
    status: 'pending',
    due_date: '2026-09-25',
  },
];
