import {
  UserProfile,
  Student,
  Teacher,
  Course,
  Subject,
  TeacherSubject,
  StudentSubject,
  AttendanceRecord,
  MarkRecord,
  Assignment,
  AssignmentSubmission,
  Exam,
  TimetableSlot,
  Notice,
  CollegeEvent,
  Certificate,
  ResumeData,
  NotificationItem,
  FeeRecord,
  HODInfo,
} from '../types';

export const INITIAL_PROFILES: UserProfile[] = [
  // Student Account (Requirement 19: student1@college.com)
  {
    id: 'user-student-1',
    full_name: 'Alex Johnson (Student 1)',
    email: 'student1@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    phone: '+1 555-0192',
    gender: 'Male',
    dob: '2003-05-14',
    address: '42 University Heights, Campus Town',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-2',
    full_name: 'Priya Sharma',
    email: 'priya.sharma@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    phone: '+1 555-0193',
    gender: 'Female',
    dob: '2003-11-20',
    address: '18 Tech Hostel, North Campus',
    created_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 'user-student-3',
    full_name: 'Rahul Patel',
    email: 'rahul.patel@college.com',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    phone: '+1 555-0194',
    gender: 'Male',
    dob: '2002-09-03',
    address: '77 Student Row, West Campus',
    created_at: '2023-08-15T00:00:00Z',
  },

  // Teacher 1 Account (Requirement 19: teacher1@college.com -> C++)
  {
    id: 'user-teacher-1',
    full_name: 'Dr. Vance (C++ Instructor)',
    email: 'teacher1@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    phone: '+1 555-0800',
    gender: 'Male',
    dob: '1980-04-12',
    address: 'Faculty Quarters A-12',
    created_at: '2021-06-10T00:00:00Z',
  },

  // Teacher 2 Account (Requirement 19: teacher2@college.com -> Mathematics)
  {
    id: 'user-teacher-2',
    full_name: 'Prof. Meera Reddy (Mathematics Instructor)',
    email: 'teacher2@college.com',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    phone: '+1 555-0801',
    gender: 'Female',
    dob: '1985-08-23',
    address: 'Faculty Quarters B-04',
    created_at: '2021-06-10T00:00:00Z',
  },

  // HOD Account (Head of Department - Computer Science)
  {
    id: 'user-hod-1',
    full_name: 'Dr. Robert Carter (HOD - Computer Science)',
    email: 'hod.cs@college.com',
    role: 'hod',
    avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150',
    phone: '+1 555-0888',
    gender: 'Male',
    dob: '1978-03-15',
    address: 'CS Department Block B, Room 204',
    created_at: '2020-01-01T00:00:00Z',
  },

  // Admin Account (Requirement 19: admin@college.com)
  {
    id: 'user-admin-1',
    full_name: 'Dr. Eleanor Vance (Institutional Admin)',
    email: 'admin@college.com',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    phone: '+1 555-0999',
    gender: 'Female',
    dob: '1975-01-05',
    address: 'Administration Block Room 101',
    created_at: '2020-01-01T00:00:00Z',
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-1',
    code: 'CSE-BTECH',
    name: 'B.Tech in Computer Science & Engineering',
    department: 'Computer Science',
    description: '4-Year undergraduate program focusing on algorithms, system design, and web software engineering.',
    duration_years: 4,
    total_semesters: 8,
    active: true,
    student_count: 140,
  },
  {
    id: 'course-2',
    code: 'IT-BTECH',
    name: 'B.Tech in Information Technology',
    department: 'Information Technology',
    description: 'Comprehensive IT degree program focusing on software architecture, cloud platforms, and security.',
    duration_years: 4,
    total_semesters: 8,
    active: true,
    student_count: 110,
  },
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'teacher-1',
    profile_id: 'user-teacher-1',
    teacher_id_code: 'TCH-1001',
    department: 'Computer Science',
    designation: 'Associate Professor',
    profile: INITIAL_PROFILES[3],
  },
  {
    id: 'teacher-2',
    profile_id: 'user-teacher-2',
    teacher_id_code: 'TCH-1002',
    department: 'Mathematics',
    designation: 'Assistant Professor',
    profile: INITIAL_PROFILES[4],
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'student-1',
    profile_id: 'user-student-1',
    student_id_code: 'STD-2023-001',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    department: 'Computer Science',
    branch: 'CSE',
    semester: 5,
    section: 'A',
    roll_number: '21CS001',
    admission_year: 2023,
    guardian_name: 'Robert Johnson Sr.',
    guardian_phone: '+1 555-9081',
    guardian_relation: 'Father',
    profile: INITIAL_PROFILES[0],
  },
  {
    id: 'student-2',
    profile_id: 'user-student-2',
    student_id_code: 'STD-2023-002',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    department: 'Computer Science',
    branch: 'CSE',
    semester: 5,
    section: 'A',
    roll_number: '21CS002',
    admission_year: 2023,
    guardian_name: 'Sunil Sharma',
    guardian_phone: '+1 555-9082',
    guardian_relation: 'Father',
    profile: INITIAL_PROFILES[1],
  },
  {
    id: 'student-3',
    profile_id: 'user-student-3',
    student_id_code: 'STD-2023-003',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    department: 'Computer Science',
    branch: 'CSE',
    semester: 5,
    section: 'B',
    roll_number: '21CS003',
    admission_year: 2023,
    guardian_name: 'Mahesh Patel',
    guardian_phone: '+1 555-9083',
    guardian_relation: 'Father',
    profile: INITIAL_PROFILES[2],
  },
];

export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: 'subj-cpp',
    code: 'CS501',
    name: 'C++ & Object-Oriented Programming',
    credits: 4,
    course_id: 'course-1',
    semester: 5,
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
  },
  {
    id: 'subj-math',
    code: 'MA502',
    name: 'Discrete Mathematics & Linear Algebra',
    credits: 4,
    course_id: 'course-1',
    semester: 5,
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy (teacher2@college.com)',
  },
  {
    id: 'subj-web',
    code: 'CS503',
    name: 'React & Modern Web Development',
    credits: 4,
    course_id: 'course-1',
    semester: 5,
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
  },
];

// Requirement 4 & 10: Teacher Subject Allocations
export const INITIAL_TEACHER_SUBJECTS: TeacherSubject[] = [
  // Teacher 1 (teacher1@college.com) -> C++ (subj-cpp) and Web Dev (subj-web)
  { id: 'ts-1', teacher_id: 'teacher-1', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501' },
  { id: 'ts-2', teacher_id: 'teacher-1', subject_id: 'subj-web', subject_name: 'React & Web Dev', subject_code: 'CS503' },

  // Teacher 2 (teacher2@college.com) -> Mathematics (subj-math) ONLY
  { id: 'ts-3', teacher_id: 'teacher-2', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502' },
];

// Student Subject Enrollments
export const INITIAL_STUDENT_SUBJECTS: StudentSubject[] = [
  { id: 'ss-1', student_id: 'student-1', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501' },
  { id: 'ss-2', student_id: 'student-1', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502' },
  { id: 'ss-3', student_id: 'student-1', subject_id: 'subj-web', subject_name: 'React & Web Dev', subject_code: 'CS503' },
  { id: 'ss-4', student_id: 'student-2', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501' },
  { id: 'ss-5', student_id: 'student-2', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502' },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // C++ Attendance (Taught by Teacher 1)
  { id: 'att-1', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501', teacher_id: 'teacher-1', date: '2026-09-01', status: 'present', marked_by: 'teacher-1' },
  { id: 'att-2', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501', teacher_id: 'teacher-1', date: '2026-09-02', status: 'present', marked_by: 'teacher-1' },
  { id: 'att-3', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-cpp', subject_name: 'C++ Programming', subject_code: 'CS501', teacher_id: 'teacher-1', date: '2026-09-03', status: 'absent', marked_by: 'teacher-1' },

  // Mathematics Attendance (Taught by Teacher 2)
  { id: 'att-4', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502', teacher_id: 'teacher-2', date: '2026-09-01', status: 'present', marked_by: 'teacher-2' },
  { id: 'att-5', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502', teacher_id: 'teacher-2', date: '2026-09-02', status: 'present', marked_by: 'teacher-2' },
  { id: 'att-6', student_id: 'student-1', student_name: 'Alex Johnson', roll_number: '21CS001', subject_id: 'subj-math', subject_name: 'Discrete Mathematics', subject_code: 'MA502', teacher_id: 'teacher-2', date: '2026-09-03', status: 'present', marked_by: 'teacher-2' },
];

export const INITIAL_MARKS: MarkRecord[] = [
  // C++ Marks (Teacher 1)
  {
    id: 'mark-1',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    roll_number: '21CS001',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    teacher_id: 'teacher-1',
    assessment_type: 'End Semester',
    semester: 5,
    internal_marks: 18,
    mid_sem_marks: 27,
    assignment_marks: 9,
    practical_marks: 19,
    end_sem_marks: 42,
    total_marks: 91,
    max_marks: 100,
    grade: 'A+',
    sgpa: 9.1,
    cgpa: 8.95,
  },
  // Mathematics Marks (Teacher 2)
  {
    id: 'mark-2',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    roll_number: '21CS001',
    subject_id: 'subj-math',
    subject_name: 'Discrete Mathematics',
    subject_code: 'MA502',
    teacher_id: 'teacher-2',
    assessment_type: 'End Semester',
    semester: 5,
    internal_marks: 19,
    mid_sem_marks: 28,
    assignment_marks: 10,
    practical_marks: 18,
    end_sem_marks: 43,
    total_marks: 94,
    max_marks: 100,
    grade: 'O',
    sgpa: 9.4,
    cgpa: 8.95,
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  // C++ Assignment (Teacher 1)
  {
    id: 'asgn-1',
    title: 'C++ Polymorphism & Memory Management',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    course_id: 'course-1',
    semester: 5,
    description: 'Implement a custom smart pointer class in C++ with reference counting and destructor cleanup.',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    created_at: '2026-09-01T10:00:00Z',
    due_date: '2026-09-15T23:59:59Z',
    max_marks: 50,
    submission_status: 'submitted',
  },
  // Mathematics Assignment (Teacher 2)
  {
    id: 'asgn-2',
    title: 'Graph Theory & Matrix Representation',
    subject_id: 'subj-math',
    subject_name: 'Discrete Mathematics',
    subject_code: 'MA502',
    course_id: 'course-1',
    semester: 5,
    description: 'Solve adjacency matrix problems and prove Euler path theorems for connected graphs.',
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy (teacher2@college.com)',
    created_at: '2026-09-03T11:30:00Z',
    due_date: '2026-09-20T23:59:59Z',
    max_marks: 100,
    submission_status: 'graded',
  },
];

export const INITIAL_SUBMISSIONS: AssignmentSubmission[] = [
  {
    id: 'sub-1',
    assignment_id: 'asgn-1',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    roll_number: '21CS001',
    submission_date: '2026-09-05T14:20:00Z',
    file_url: 'https://storage.university.edu/submissions/cpp-smart-pointer.cpp',
    remarks: 'Excellent RAII design pattern implementation!',
    grade: 48,
    status: 'graded',
  },
  {
    id: 'sub-2',
    assignment_id: 'asgn-2',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    roll_number: '21CS001',
    submission_date: '2026-09-04T18:10:00Z',
    file_url: 'https://storage.university.edu/submissions/graph-theory.pdf',
    remarks: 'Flawless mathematical proof of Eulerian graphs.',
    grade: 96,
    status: 'graded',
  },
];

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-1',
    name: 'C++ Object-Oriented Practical Examination',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    teacher_id: 'teacher-1',
    exam_type: 'practical',
    exam_date: '2026-10-05',
    start_time: '10:00:00',
    end_time: '12:00:00',
    duration: '2 Hours',
    room: 'Lab 4B',
    instructions: 'Live C++ coding test. Compile with g++ -std=c++20.',
    max_marks: 50,
  },
  {
    id: 'exam-2',
    name: 'Discrete Mathematics Mid-Semester Written Exam',
    subject_id: 'subj-math',
    subject_name: 'Discrete Mathematics',
    teacher_id: 'teacher-2',
    exam_type: 'mid_sem',
    exam_date: '2026-10-08',
    start_time: '14:00:00',
    end_time: '17:00:00',
    duration: '3 Hours',
    room: 'Hall 302',
    instructions: 'Calculators permitted. Show detailed steps for all proof questions.',
    max_marks: 50,
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  // B.Tech CSE, Semester 5, Section A
  {
    id: 'tt-1',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Monday',
    start_time: '09:00',
    end_time: '10:00',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Lab 4B',
    type: 'Lab',
    status: 'Published',
  },
  {
    id: 'tt-2',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Monday',
    start_time: '10:15',
    end_time: '11:15',
    subject_id: 'subj-math',
    subject_name: 'Discrete Math',
    subject_code: 'MA502',
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy (teacher2@college.com)',
    room: 'Hall 302',
    type: 'Lecture',
    status: 'Published',
  },
  {
    id: 'tt-3',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Tuesday',
    start_time: '09:00',
    end_time: '10:00',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Room 301',
    type: 'Lecture',
    status: 'Published',
  },
  {
    id: 'tt-4',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Tuesday',
    start_time: '11:30',
    end_time: '12:30',
    subject_id: 'subj-web',
    subject_name: 'React & Web Dev',
    subject_code: 'CS503',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Lab 2',
    type: 'Practical',
    status: 'Published',
  },
  {
    id: 'tt-5',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Wednesday',
    start_time: '10:00',
    end_time: '11:00',
    subject_id: 'subj-math',
    subject_name: 'Discrete Math',
    subject_code: 'MA502',
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy (teacher2@college.com)',
    room: 'Room 204',
    type: 'Lecture',
    status: 'Published',
  },
  {
    id: 'tt-6',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Thursday',
    start_time: '09:00',
    end_time: '10:00',
    subject_id: 'subj-web',
    subject_name: 'React & Web Dev',
    subject_code: 'CS503',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Lab 4B',
    type: 'Lab',
    status: 'Published',
  },
  {
    id: 'tt-7',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'A',
    day: 'Friday',
    start_time: '10:00',
    end_time: '11:00',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Room 301',
    type: 'Lecture',
    status: 'Published',
  },

  // B.Tech CSE, Semester 5, Section B
  {
    id: 'tt-8',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'B',
    day: 'Monday',
    start_time: '11:30',
    end_time: '12:30',
    subject_id: 'subj-cpp',
    subject_name: 'C++ Programming',
    subject_code: 'CS501',
    teacher_id: 'teacher-1',
    teacher_name: 'Dr. Vance (teacher1@college.com)',
    room: 'Lab 4B',
    type: 'Lab',
    status: 'Published',
  },
  {
    id: 'tt-9',
    course_id: 'course-1',
    course_name: 'B.Tech CSE',
    semester: 5,
    section: 'B',
    day: 'Tuesday',
    start_time: '10:15',
    end_time: '11:15',
    subject_id: 'subj-math',
    subject_name: 'Discrete Math',
    subject_code: 'MA502',
    teacher_id: 'teacher-2',
    teacher_name: 'Prof. Meera Reddy (teacher2@college.com)',
    room: 'Hall 302',
    type: 'Lecture',
    status: 'Published',
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not-1',
    title: 'Mid-Semester Datesheet Released by HOD',
    description: 'The finalized mid-semester exam datesheet for CS & IT departments has been published by HOD Office.',
    category: 'Exam',
    priority: 'Urgent',
    publish_date: '2026-09-06',
    expiry_date: '2026-10-15',
    author_name: 'HOD Office (admin@college.com)',
    pinned: true,
    archived: false,
  },
];

export const INITIAL_EVENTS: CollegeEvent[] = [
  {
    id: 'evt-1',
    title: 'National Technology Conference 2026',
    description: 'Keynote sessions on modern software engineering, AI, and cloud architectures.',
    event_type: 'College Event',
    start_date: '2026-09-22T09:00:00Z',
    end_date: '2026-09-23T21:00:00Z',
    location: 'Main Campus Auditorium',
  },
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-1',
    student_id: 'student-1',
    student_name: 'Alex Johnson',
    name: 'AWS Certified Cloud Practitioner',
    organization: 'Amazon Web Services',
    issue_date: '2026-06-15',
    certificate_code: 'AWS-CCP-884920',
    credential_url: 'https://aws.amazon.com/verification',
    category: 'Technical',
    description: 'Validated AWS Cloud security, core architecture, and deployment.',
    file_url: 'https://images.unsplash.com/photo-1589330694653-aded6fac0243?w=500',
    status: 'verified',
    remarks: 'Verified by Admin (Dr. Eleanor Vance).',
  },
];

export const INITIAL_RESUME: ResumeData = {
  id: 'res-1',
  student_id: 'student-1',
  full_name: 'Alex Johnson',
  email: 'student1@college.com',
  phone: '+1 (555) 019-2834',
  location: 'San Francisco, CA',
  linkedin: 'https://linkedin.com/in/alexjohnson-dev',
  github: 'https://github.com/alexjohnson',
  portfolio: 'https://alexjohnson.dev',
  summary: 'Computer Science student skilled in C++, React, TypeScript, and Data Structures. Passionate about software architecture and full-stack web systems.',
  template_id: 'modern',
  education: [
    {
      id: 'edu-1',
      degree: 'B.Tech in Computer Science & Engineering',
      university: 'State Technological University',
      course: 'Computer Science',
      start_year: '2023',
      end_year: '2027',
      grade: 'CGPA: 8.95 / 10.0',
    },
  ],
  skills: [
    { id: 'sk-1', category: 'Languages', items: ['C++', 'JavaScript', 'TypeScript', 'SQL', 'HTML/CSS'] },
    { id: 'sk-2', category: 'Frameworks', items: ['React.js', 'Tailwind CSS', 'Node.js', 'Supabase'] },
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'Smart Student Management System',
      description: 'Built a full role-based portal with Supabase integration, attendance tracking, and AI career guidance.',
      technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Supabase'],
    },
  ],
  internships: [],
  certificates: [
    {
      id: 'cert-r-1',
      name: 'AWS Certified Cloud Practitioner',
      organization: 'Amazon Web Services',
      date: 'June 2026',
    },
  ],
  achievements: ['Dean’s Honor List for 5th Semester'],
  languages: ['English'],
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'user-student-1',
    title: 'New Assignment Published in C++',
    message: 'Dr. Vance published C++ Polymorphism assignment.',
    type: 'assignment',
    is_read: false,
    created_at: '2026-09-06T08:00:00Z',
  },
];

export const INITIAL_HODS: HODInfo[] = [
  {
    id: 'hod-1',
    profile_id: 'user-hod-1',
    hod_id_code: 'HOD-CS-001',
    department: 'Computer Science',
    profile: INITIAL_PROFILES.find(p => p.id === 'user-hod-1'),
  },
];

export const INITIAL_FEES: FeeRecord[] = [
  {
    id: 'fee-1',
    student_id: 'student-1',
    student_name: 'Alex Johnson (Student 1)',
    roll_number: '23CS101',
    department: 'Computer Science',
    semester: 5,
    academic_year: '2025-2026',
    tuition_fee: 45000,
    exam_fee: 3500,
    library_fee: 1500,
    total_amount: 50000,
    paid_amount: 50000,
    status: 'paid',
    due_date: '2026-08-30',
    receipt_no: 'REC-2026-08912',
    paid_at: '2026-08-15T10:30:00Z',
  },
  {
    id: 'fee-2',
    student_id: 'student-2',
    student_name: 'Priya Sharma',
    roll_number: '23CS102',
    department: 'Computer Science',
    semester: 5,
    academic_year: '2025-2026',
    tuition_fee: 45000,
    exam_fee: 3500,
    library_fee: 1500,
    total_amount: 50000,
    paid_amount: 25000,
    status: 'partial',
    due_date: '2026-09-30',
  },
  {
    id: 'fee-3',
    student_id: 'student-3',
    student_name: 'Rahul Patel',
    roll_number: '23CS103',
    department: 'Computer Science',
    semester: 5,
    academic_year: '2025-2026',
    tuition_fee: 45000,
    exam_fee: 3500,
    library_fee: 1500,
    total_amount: 50000,
    paid_amount: 0,
    status: 'pending',
    due_date: '2026-09-25',
  },
];
